import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import axios from "axios";
import { setFeedPosts } from "@/state/slices/post";
import { Button } from "@saas-ui/react";
import {
  Avatar,
  AvatarGroup,
  Box,
  Divider,
  Flex,
  HStack,
  Spacer,
  Text,
  useColorMode,
} from "@chakra-ui/react";
import PostWidget from "@/components/post/PostWidget";
import MyPostWidget from "@/components/post/MyPostWidget";
import SessionEnd from "@/components/toasts/SessionEnd";
import PageLayout from "@/views/Sidebar";
export default function Home() {
  const dispatch = useDispatch();
  const feed = useSelector((state) => state.post.feed);

  useEffect(() => {
    const init = async () => {
      await axios
        .get("https://api.defitalks.io/api/post/feed")
        .then((res) => {
          if (res.status === 200) {
            dispatch(setFeedPosts(res.data));
          } else {
            console.log("Error");
          }
        })
        .catch((err) => {
          console.log(err);
        });
    };
    init();
  }, []);
  return (
    <>
      <Head>
        <title>Defi Talks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout title={"Homepage"}>
        <MyPostWidget />
        {feed && feed.map((post) => <PostWidget key={post._id} post={post} />)}
      </PageLayout>
    </>
  );
}
